import { Component } from '@angular/core';
import { Elm327Service } from '../services/elm327.service';
import { Storage } from '@ionic/storage-angular';
import { Platform } from '@ionic/angular';


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  public strStatusBlue : any;
  public strStatusConn : any;
  hexValue = '';
  convertedTemperature: number | null = null;

  convert() {
    this.convertedTemperature = this.convertAirTemperature(this.hexValue);
  }

   convertAirTemperature(hexValue: string): number | null {
    hexValue = hexValue.replace(/\s/g, '');
    const hexPairs = hexValue.match(/.{1,2}/g);

    if (hexPairs && hexPairs[0] === '41' && hexPairs[1] === '0E' && hexPairs.length === 4) {
      const temperature = parseInt(hexPairs[2], 16) - 40;

      console.log('Temperatura convertida : ', temperature);
      return temperature;
    }

    return null;
  }
  public comandos = [ { "id_medida": "1","ordem": "1","Status": "A","comando": "ATE0","valor_hex": null,"valor_texto": null,"nome_medida": "Echo on/off","desc_medida": "Echo on/off","tamanho_medida": "1","fnc_conversao": "n/a","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "2","ordem": "2","Status": "A","comando": "ATZ","valor_hex": null,"valor_texto": null,"nome_medida": "Reset","desc_medida": "Reset","tamanho_medida": "1","fnc_conversao": "n/a","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      //{"id_medida": "3","ordem": "3","Status": "A","comando": "ATSP0","valor_hex": null,"valor_texto": null,"nome_medida": "Def. Protocolo","desc_medida": "Def. Protocolo","tamanho_medida": "1","fnc_conversao": "n/a","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "4","ordem": "4","Status": "A","comando": "ATI","valor_hex": null,"valor_texto": null,"nome_medida": "Adaptador","desc_medida": "Adaptador / versao","tamanho_medida": "1","fnc_conversao": "n/a","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "5","ordem": "5","Status": "A","comando": "ATDP","valor_hex": null,"valor_texto": null,"nome_medida": "Protocolo","desc_medida": "Protocolo","tamanho_medida": "1","fnc_conversao": "n/a","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "100","ordem": "6","Status": "A","comando": "0104","valor_hex": null,"valor_texto": null,"nome_medida": "load_pct","desc_medida": "Calculated LOAD Value","tamanho_medida": "1","fnc_conversao": "convertLoad","unidade_medida": null,"sigla_medida": null,"min": "0","max": "100"},
                      {"id_medida": "101","ordem": "7","Status": "A","comando": "0100","valor_hex": null,"valor_texto": null,"nome_medida": "pidsupp0","desc_medida": "PIDs supported 00-20","tamanho_medida": "4","fnc_conversao": "convertPIDSupported","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "102","ordem": "8","Status": "A","comando": "0101","valor_hex": null,"valor_texto": null,"nome_medida": "dtc_cnt","desc_medida": "Monitor status since DTCs cleared","tamanho_medida": "4","fnc_conversao": "convertDTCCheck","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "103","ordem": "9","Status": "A","comando": "0102","valor_hex": null,"valor_texto": null,"nome_medida": "dtcfrzf","desc_medida": "DTC that caused required freeze frame data storage","tamanho_medida": "2","fnc_conversao": "bitDecoder","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
                      {"id_medida": "104","ordem": "10","Status": "A","comando": "0103","valor_hex": null,"valor_texto": null,"nome_medida": "fuelsys","desc_medida": "Fuel system 1 and 2 status","tamanho_medida": "2","fnc_conversao": "convertFuelSystem","unidade_medida": null,"sigla_medida": null,"min": "0","max": "0"},
{
"id_medida": "106",
"ordem": "11",
"Status": "A",
"comando": "0105",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "temp",
"desc_medida": "Engine Coolant Temperature",
"tamanho_medida": "1",
"fnc_conversao": "convertTemp",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "107",
"ordem": "12",
"Status": "A",
"comando": "0106",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "shrtft13",
"desc_medida": "Short Term Fuel Trim - Bank 1,3",
"tamanho_medida": "1",
"fnc_conversao": "convertFuelTrim",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "108",
"ordem": "13",
"Status": "A",
"comando": "0107",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "longft13",
"desc_medida": "Long Term Fuel Trim - Bank 1,3",
"tamanho_medida": "1",
"fnc_conversao": "convertFuelTrim",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "109",
"ordem": "14",
"Status": "A",
"comando": "0108",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "shrtft24",
"desc_medida": "Short Term Fuel Trim - Bank 2,4",
"tamanho_medida": "1",
"fnc_conversao": "convertFuelTrim",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "110",
"ordem": "15",
"Status": "A",
"comando": "0109",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "longft24",
"desc_medida": "Long Term Fuel Trim - Bank 2,4",
"tamanho_medida": "1",
"fnc_conversao": "convertFuelTrim",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "111",
"ordem": "16",
"Status": "A",
"comando": "010A",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "frp",
"desc_medida": "Fuel Pressure",
"tamanho_medida": "1",
"fnc_conversao": "convertFuelRailPressure",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "765"
},
{
"id_medida": "112",
"ordem": "17",
"Status": "A",
"comando": "010B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "map",
"desc_medida": "Intake Manifold Absolute Pressure",
"tamanho_medida": "1",
"fnc_conversao": "convertIntakePressure",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "255"
},
{
"id_medida": "113",
"ordem": "18",
"Status": "A",
"comando": "010C",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "rpm",
"desc_medida": "Engine RPM",
"tamanho_medida": "2",
"fnc_conversao": "convertRPM",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "16384"
},
{
"id_medida": "114",
"ordem": "19",
"Status": "A",
"comando": "010D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "vss",
"desc_medida": "Vehicle Speed Sensor",
"tamanho_medida": "1",
"fnc_conversao": "convertSpeed",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "255"
},
{
"id_medida": "115",
"ordem": "20",
"Status": "A",
"comando": "010E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "sparkadv",
"desc_medida": "Ignition Timing Advance for #1 Cylinder",
"tamanho_medida": "1",
"fnc_conversao": "convertSparkAdvance",
"unidade_medida": null,
"sigla_medida": null,
"min": "-64",
"max": "64"
},
{
"id_medida": "116",
"ordem": "21",
"Status": "A",
"comando": "010F",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "iat",
"desc_medida": "Intake Air Temperature",
"tamanho_medida": "1",
"fnc_conversao": "convertTemp",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "117",
"ordem": "22",
"Status": "A",
"comando": "0110",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "maf",
"desc_medida": "Air Flow Rate from Mass Air Flow Sensor",
"tamanho_medida": "2",
"fnc_conversao": "convertAirFlowRate",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "655"
},
{
"id_medida": "118",
"ordem": "23",
"Status": "A",
"comando": "0111",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "throttlepos",
"desc_medida": "Absolute Throttle Position",
"tamanho_medida": "1",
"fnc_conversao": "convertThrottlePos",
"unidade_medida": null,
"sigla_medida": null,
"min": "1",
"max": "100"
},
{
"id_medida": "119",
"ordem": "24",
"Status": "A",
"comando": "0112",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "air_stat",
"desc_medida": "Commanded Secondary Air Status",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "120",
"ordem": "25",
"Status": "A",
"comando": "0113",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2sloc",
"desc_medida": "Location of Oxygen Sensors",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "121",
"ordem": "26",
"Status": "A",
"comando": "0114",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s11",
"desc_medida": "Oxygen Sensor Bank 1 - Sensor 1",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "122",
"ordem": "27",
"Status": "A",
"comando": "0115",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s12",
"desc_medida": "Oxygen Sensor Bank 1 - Sensor 2",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "123",
"ordem": "28",
"Status": "A",
"comando": "0116",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s13",
"desc_medida": "Oxygen Sensor Bank 1 - Sensor 3",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "124",
"ordem": "29",
"Status": "A",
"comando": "0117",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s14",
"desc_medida": "Oxygen Sensor Bank 1 - Sensor 4",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "125",
"ordem": "30",
"Status": "A",
"comando": "0118",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s21",
"desc_medida": "Oxygen Sensor Bank 2 - Sensor 1",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "126",
"ordem": "31",
"Status": "A",
"comando": "0119",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s22",
"desc_medida": "Oxygen Sensor Bank 2 - Sensor 2",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "127",
"ordem": "32",
"Status": "A",
"comando": "011A",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s23",
"desc_medida": "Oxygen Sensor Bank 2 - Sensor 3",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "128",
"ordem": "33",
"Status": "A",
"comando": "011B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2s24",
"desc_medida": "Oxygen Sensor Bank 2 - Sensor 4",
"tamanho_medida": "2",
"fnc_conversao": "convertOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "1275"
},
{
"id_medida": "129",
"ordem": "34",
"Status": "A",
"comando": "011C",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "obdsup",
"desc_medida": "OBD requirements to which vehicle is designed",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "130",
"ordem": "35",
"Status": "A",
"comando": "011D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "o2sloc2",
"desc_medida": "Location of oxygen sensors",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "131",
"ordem": "36",
"Status": "A",
"comando": "011E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "pto_stat",
"desc_medida": "Auxiliary Input Status",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "132",
"ordem": "37",
"Status": "A",
"comando": "011F",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "runtm",
"desc_medida": "Time Since Engine Start",
"tamanho_medida": "2",
"fnc_conversao": "convertRuntime",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "65535"
},
{
"id_medida": "133",
"ordem": "38",
"Status": "A",
"comando": "0120",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "piddsupp2",
"desc_medida": "PIDs supported 21-40",
"tamanho_medida": "4",
"fnc_conversao": "convertPIDSupported",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "134",
"ordem": "39",
"Status": "A",
"comando": "0121",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "mil_dist",
"desc_medida": "Distance Travelled While MIL is Activated",
"tamanho_medida": "2",
"fnc_conversao": "convertRuntime",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "65535"
},
{
"id_medida": "135",
"ordem": "40",
"Status": "A",
"comando": "0122",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "frpm",
"desc_medida": "Fuel Rail Pressure relative to manifold vacuum",
"tamanho_medida": "2",
"fnc_conversao": "convertfrpm",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "5177265"
},
{
"id_medida": "136",
"ordem": "41",
"Status": "A",
"comando": "0123",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "frpd",
"desc_medida": "Fuel Rail Pressure (diesel)",
"tamanho_medida": "2",
"fnc_conversao": "convertfrpd",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "655350"
},
{
"id_medida": "137",
"ordem": "42",
"Status": "A",
"comando": "0124",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda11",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 1/Bank 1 - Sensor 1 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "138",
"ordem": "43",
"Status": "A",
"comando": "0125",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda12",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 2/Bank 1 - Sensor 2 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "139",
"ordem": "44",
"Status": "A",
"comando": "0126",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda13",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 3 /Bank 2 - Sensor 1",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "140",
"ordem": "45",
"Status": "A",
"comando": "0127",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda14",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 4 /Bank 2 - Sensor 2",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "141",
"ordem": "46",
"Status": "A",
"comando": "0128",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda21",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 1 /Bank 3 - Sensor 1",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "142",
"ordem": "47",
"Status": "A",
"comando": "0129",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda22",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 2 /Bank 3 - Sensor 2",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "143",
"ordem": "48",
"Status": "A",
"comando": "012A",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda23",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 3 /Bank 4 - Sensor 1",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "144",
"ordem": "49",
"Status": "A",
"comando": "012B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda24",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 4 /Bank 4 - Sensor 2",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "145",
"ordem": "50",
"Status": "A",
"comando": "012C",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "egr_pct",
"desc_medida": "Commanded EGR",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "146",
"ordem": "51",
"Status": "A",
"comando": "012D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "egr_err",
"desc_medida": "EGR Error",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentB",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "147",
"ordem": "52",
"Status": "A",
"comando": "012E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "evap_pct",
"desc_medida": "Commanded Evaporative Purge",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "148",
"ordem": "53",
"Status": "A",
"comando": "012F",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "fli",
"desc_medida": "Fuel Level Input",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "149",
"ordem": "54",
"Status": "A",
"comando": "0130",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "warm_ups",
"desc_medida": "Number of warm-ups since diagnostic trouble codes cleared",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "255"
},
{
"id_medida": "150",
"ordem": "55",
"Status": "A",
"comando": "0131",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "clr_dist",
"desc_medida": "Distance since diagnostic trouble codes cleared",
"tamanho_medida": "2",
"fnc_conversao": "convertDistanceSinceCodesCleared",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "65535"
},
{
"id_medida": "151",
"ordem": "56",
"Status": "A",
"comando": "0132",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "evap_vp",
"desc_medida": "Evap System Vapour Pressure",
"tamanho_medida": "2",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "-8192",
"max": "8192"
},
{
"id_medida": "152",
"ordem": "57",
"Status": "A",
"comando": "0133",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "baro",
"desc_medida": "Barometric Pressure",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "255"
},
{
"id_medida": "153",
"ordem": "58",
"Status": "A",
"comando": "0134",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac11",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 1/Bank 1 - Sensor 1 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "154",
"ordem": "59",
"Status": "A",
"comando": "0135",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac12",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 2/Bank 1 - Sensor 2 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "155",
"ordem": "60",
"Status": "A",
"comando": "0136",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac13",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 3/Bank 2 - Sensor 1 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "156",
"ordem": "61",
"Status": "A",
"comando": "0137",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac14",
"desc_medida": "Oxygen Sensors (lambda) Bank 1 - Sensor 4/Bank 2 - Sensor 2 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "157",
"ordem": "62",
"Status": "A",
"comando": "0138",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac21",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 1/Bank 3 - Sensor 1 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "158",
"ordem": "63",
"Status": "A",
"comando": "0139",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac22",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 2/Bank 3 - Sensor 2 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "159",
"ordem": "64",
"Status": "A",
"comando": "013A",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac23",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 3/Bank 4 - Sensor 1 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "160",
"ordem": "65",
"Status": "A",
"comando": "013B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambdac24",
"desc_medida": "Oxygen Sensors (lambda) Bank 2 - Sensor 4/Bank 4 - Sensor 2 ",
"tamanho_medida": "4",
"fnc_conversao": "convertLambda2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "161",
"ordem": "66",
"Status": "A",
"comando": "013C",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "catemp11",
"desc_medida": "Catalyst Temperature Bank 1 / Sensor 1",
"tamanho_medida": "2",
"fnc_conversao": "convertCatalystTemperature",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "6514"
},
{
"id_medida": "162",
"ordem": "67",
"Status": "A",
"comando": "013D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "catemp21",
"desc_medida": "Catalyst Temperature Bank 2 / Sensor 1",
"tamanho_medida": "2",
"fnc_conversao": "convertCatalystTemperature",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "6514"
},
{
"id_medida": "163",
"ordem": "68",
"Status": "A",
"comando": "013E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "catemp12",
"desc_medida": "Catalyst Temperature Bank 1 / Sensor 2",
"tamanho_medida": "2",
"fnc_conversao": "convertCatalystTemperature",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "6514"
},
{
"id_medida": "164",
"ordem": "69",
"Status": "A",
"comando": "013F",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "catemp22",
"desc_medida": "Catalyst Temperature Bank 2 / Sensor 2",
"tamanho_medida": "2",
"fnc_conversao": "convertCatalystTemperature",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "6514"
},
{
"id_medida": "165",
"ordem": "70",
"Status": "A",
"comando": "0140",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "piddsupp4",
"desc_medida": "PIDs supported 41-60",
"tamanho_medida": "4",
"fnc_conversao": "convertPIDSupported",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "166",
"ordem": "71",
"Status": "A",
"comando": "0141",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "monitorstat",
"desc_medida": "Monitor status this driving cycle",
"tamanho_medida": "4",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "167",
"ordem": "72",
"Status": "A",
"comando": "0142",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "vpwr",
"desc_medida": "Control module voltage",
"tamanho_medida": "2",
"fnc_conversao": "convertControlModuleVoltage",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "65535"
},
{
"id_medida": "168",
"ordem": "73",
"Status": "A",
"comando": "0143",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "load_abs",
"desc_medida": "Absolute Load Value",
"tamanho_medida": "2",
"fnc_conversao": "convertAbsoluteLoad",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "25700"
},
{
"id_medida": "169",
"ordem": "74",
"Status": "A",
"comando": "0144",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "lambda",
"desc_medida": "Fuel/air Commanded Equivalence Ratio",
"tamanho_medida": "2",
"fnc_conversao": "convertLambda3",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "2"
},
{
"id_medida": "170",
"ordem": "75",
"Status": "A",
"comando": "0145",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "tp_r",
"desc_medida": "Relative Throttle Position",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "171",
"ordem": "76",
"Status": "A",
"comando": "0146",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "aat",
"desc_medida": "Ambient air temperature",
"tamanho_medida": "1",
"fnc_conversao": "convertAmbientAirTemp",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "172",
"ordem": "77",
"Status": "A",
"comando": "0147",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "tp_b",
"desc_medida": "Absolute Throttle Position B",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "173",
"ordem": "78",
"Status": "A",
"comando": "0148",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "tp_c",
"desc_medida": "Absolute Throttle Position C",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "174",
"ordem": "79",
"Status": "A",
"comando": "0149",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "app_d",
"desc_medida": "Accelerator Pedal Position D",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "175",
"ordem": "80",
"Status": "A",
"comando": "014A",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "app_e",
"desc_medida": "Accelerator Pedal Position E",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "176",
"ordem": "81",
"Status": "A",
"comando": "014B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "app_f",
"desc_medida": "Accelerator Pedal Position F",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "177",
"ordem": "82",
"Status": "A",
"comando": "014C",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "tac_pct",
"desc_medida": "Commanded Throttle Actuator Control",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "178",
"ordem": "83",
"Status": "A",
"comando": "014D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "mil_time",
"desc_medida": "Time run by the engine while MIL activated",
"tamanho_medida": "2",
"fnc_conversao": "convertMinutes",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "65535"
},
{
"id_medida": "179",
"ordem": "84",
"Status": "A",
"comando": "014E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "clr_time",
"desc_medida": "Time since diagnostic trouble codes cleared",
"tamanho_medida": "2",
"fnc_conversao": "convertMinutes",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "65535"
},
{
"id_medida": "180",
"ordem": "85",
"Status": "A",
"comando": "014F",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "exttest1",
"desc_medida": "External Test Equipment Configuration #1",
"tamanho_medida": "4",
"fnc_conversao": "convertExternalTestEquipment",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "181",
"ordem": "86",
"Status": "A",
"comando": "0150",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "exttest2",
"desc_medida": "External Test Equipment Configuration #2",
"tamanho_medida": "4",
"fnc_conversao": "convertExternalTestEquipment2",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "182",
"ordem": "87",
"Status": "A",
"comando": "0151",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "fuel_type",
"desc_medida": "Fuel Type",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "183",
"ordem": "88",
"Status": "A",
"comando": "0152",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "alch_pct",
"desc_medida": "Ethanol fuel %",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "184",
"ordem": "89",
"Status": "A",
"comando": "0153",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "abs_vp",
"desc_medida": "Absolute Evap system Vapor Pressure",
"tamanho_medida": "2",
"fnc_conversao": "convertAbsoluteVaporPressure",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "327675"
},
{
"id_medida": "185",
"ordem": "90",
"Status": "A",
"comando": "0154",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "system_vp",
"desc_medida": "Evap system vapor pressure",
"tamanho_medida": "2",
"fnc_conversao": "convertSystemVaporPressure",
"unidade_medida": null,
"sigla_medida": null,
"min": "-32767",
"max": "32767"
},
{
"id_medida": "186",
"ordem": "91",
"Status": "A",
"comando": "0155",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "s02b13",
"desc_medida": "Short term secondary oxygen sensor trim bank 1 and bank 3",
"tamanho_medida": "2",
"fnc_conversao": "convertShortOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "187",
"ordem": "92",
"Status": "A",
"comando": "0156",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "l02b13",
"desc_medida": "Long term secondary oxygen sensor trim bank 1 and bank 3",
"tamanho_medida": "2",
"fnc_conversao": "convertShortOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "188",
"ordem": "93",
"Status": "A",
"comando": "0157",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "s02b24",
"desc_medida": "Short term secondary oxygen sensor trim bank 2 and bank 4",
"tamanho_medida": "2",
"fnc_conversao": "convertShortOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "189",
"ordem": "94",
"Status": "A",
"comando": "0158",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "l02b24",
"desc_medida": "Long term secondary oxygen sensor trim bank 2 and bank 4",
"tamanho_medida": "2",
"fnc_conversao": "convertShortOxygenSensorOutput",
"unidade_medida": null,
"sigla_medida": null,
"min": "-100",
"max": "99"
},
{
"id_medida": "190",
"ordem": "95",
"Status": "A",
"comando": "0159",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "frp_abs",
"desc_medida": "Fuel rail pressure (absolute)",
"tamanho_medida": "2",
"fnc_conversao": "convertFuelRailPressureAbs",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "655350"
},
{
"id_medida": "191",
"ordem": "96",
"Status": "A",
"comando": "015A",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "pedalpos",
"desc_medida": "Relative accelerator pedal position",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "192",
"ordem": "97",
"Status": "A",
"comando": "015B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "hybridlife",
"desc_medida": "Hybrid battery pack remaining life",
"tamanho_medida": "1",
"fnc_conversao": "convertPercentA",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "100"
},
{
"id_medida": "193",
"ordem": "98",
"Status": "A",
"comando": "015C",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "engineoilt",
"desc_medida": "Engine oil temperature",
"tamanho_medida": "1",
"fnc_conversao": "convertTemp",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "210"
},
{
"id_medida": "194",
"ordem": "99",
"Status": "A",
"comando": "015D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "finjtiming",
"desc_medida": "Fuel injection timing",
"tamanho_medida": "2",
"fnc_conversao": "convertFuelInjectionTiming",
"unidade_medida": null,
"sigla_medida": null,
"min": "-210",
"max": "301992"
},
{
"id_medida": "195",
"ordem": "100",
"Status": "A",
"comando": "015E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "enginefrate",
"desc_medida": "Engine fuel rate",
"tamanho_medida": "2",
"fnc_conversao": "convertEngineFuelRate",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "3213"
},
{
"id_medida": "196",
"ordem": "101",
"Status": "A",
"comando": "015F",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "emmissionreq",
"desc_medida": "Emission requirements to which vehicle is designed",
"tamanho_medida": "1",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "197",
"ordem": "102",
"Status": "A",
"comando": "0162",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "aet",
"desc_medida": "Actual engine - percent torque",
"tamanho_medida": "1",
"fnc_conversao": "convertEngineTorque",
"unidade_medida": null,
"sigla_medida": null,
"min": "-125",
"max": "125"
},
{
"id_medida": "198",
"ordem": "103",
"Status": "A",
"comando": "0167",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "ect",
"desc_medida": "Engine coolant temperature",
"tamanho_medida": "3",
"fnc_conversao": "n/a",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "199",
"ordem": "104",
"Status": "A",
"comando": "016B",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "egrt",
"desc_medida": "Exhaust gas recirculation temperature",
"tamanho_medida": "5",
"fnc_conversao": "n/a",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "200",
"ordem": "105",
"Status": "A",
"comando": "016D",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "fpc",
"desc_medida": "Fuel pressure control system",
"tamanho_medida": "6",
"fnc_conversao": "n/a",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "201",
"ordem": "106",
"Status": "A",
"comando": "016E",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "ipct",
"desc_medida": "Injection pressure control system",
"tamanho_medida": "5",
"fnc_conversao": "n/a",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "202",
"ordem": "107",
"Status": "A",
"comando": "0173",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "ep",
"desc_medida": "Exhaust pressure",
"tamanho_medida": "5",
"fnc_conversao": "n/a",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "203",
"ordem": "108",
"Status": "A",
"comando": "0178",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "egt",
"desc_medida": "Exhaust Gas temperature Bank 1",
"tamanho_medida": "9",
"fnc_conversao": "convertExhastGasTemperature",
"unidade_medida": null,
"sigla_medida": null,
"min": "-40",
"max": "215"
},
{
"id_medida": "204",
"ordem": "1099",
"Status": "A",
"comando": "03",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "requestdtc",
"desc_medida": "Requested DTC",
"tamanho_medida": "6",
"fnc_conversao": "convertDTCRequest",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "205",
"ordem": "1109",
"Status": "A",
"comando": "04",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "cleardtc",
"desc_medida": "Clear Trouble Codes (Clear engine light)",
"tamanho_medida": "0",
"fnc_conversao": "notSupported",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "206",
"ordem": "11199",
"Status": "A",
"comando": "0900",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "vinsupp0",
"desc_medida": "Vehicle Identification Number",
"tamanho_medida": "4",
"fnc_conversao": "bitDecoder",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "207",
"ordem": "11299",
"Status": "A",
"comando": "0901",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "vin_mscout",
"desc_medida": "VIN message count",
"tamanho_medida": "1",
"fnc_conversao": "convertVIN_count",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
},
{
"id_medida": "208",
"ordem": "11399",
"Status": "A",
"comando": "0902",
"valor_hex": null,
"valor_texto": null,
"nome_medida": "vin",
"desc_medida": "Vehicle Identification Number",
"tamanho_medida": "1",
"fnc_conversao": "convertVIN",
"unidade_medida": null,
"sigla_medida": null,
"min": "0",
"max": "0"
}
]
;

  constructor(private storage: Storage, private platform: Platform, private elm327Service: Elm327Service) {
    this.platform.ready().then(() => {
      this.storage.create();
    } );
  }

  async saveComandos() {
    console.log('Salvar comandos : ', this.comandos);
    this.storage.set('comandos', this.comandos);
  }

  async getComandos() {
    this.comandos = await this.storage.get('comandos');
    console.log('Restaurar comandos : ', this.comandos);
  }

  async connectToElm327(  ) {
    await this.elm327Service.connectToElm327(this.comandos);

    //await this.elm327Service.connectToElm327();
    if ( this.elm327Service.bisConnected ) {
      this.strStatusConn = 'Conectado';
    }else{
      this.strStatusConn = 'Desconectado';
    }
    if ( this.elm327Service.bBlueToothEnable){
      this.strStatusBlue = 'Ativo';
    }else{
      this.strStatusBlue = 'Desligado';
    }
  }

}
